external_components:
  - source:
      type: local
      path: "/config/components"


esphome:
  name: rmtuarttest
  friendly_name: ESP32 RMT UART Test


esp32:
  board: esp32dev
  framework:
    type: esp-idf
  # Does it also work with the Arduino framework?
  # framework:
  #   type: arduino

# Enable logging
logger:
  level: DEBUG 
  baud_rate: 0
  # logs:
  #   huawei_r4850: VERBOSE


    

  


esp32rmtuart:
    id: rmt1 
    tx_pin: 1
    rx_pin: 3
    # tested baud_rate
    # baud_rate: 19200
    # baud_rate: 38400
    # baud_rate: 57600
    baud_rate: 115200
    # baud_rate: 230400
    # baud_rate: 460800
    # baud_rate: 921600
    stop_bits: 1
    data_bits: 8
    parity: NONE
    rmt_rx_symbols: 192

modbus:
  # flow_control_pin: GPIOXX
  id: modbus1
  uart_id: rmt1

modbus_controller:
- id: modbus_device
  address: 0x1   ## address of the Modbus slave device on the bus
  modbus_id: modbus1
  setup_priority: -10
  update_interval: 00.5s

sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "test1"
  register_type: holding
  address: 0x01    ## address of the register inside the Modbus slave device
  unit_of_measurement: "oorbellen"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "test2"
  register_type: holding
  address: 0x02    ## address of the register inside the Modbus slave device
  unit_of_measurement: "oorbellen"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "test10"
  register_type: holding
  address: 0x10    ## address of the register inside the Modbus slave device
  unit_of_measurement: "oorbellen"
  value_type: U_WORD
  register_count: 10